upstream php_backend {
    server php-fpm:9000;
}

server {
    listen 80;
    server_name localhost;

    root /var/www/frontend;
    index index.html;

    location /api/ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_pass php_backend;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
